### ISSUE TITLE
verify_certificate

### ISSUE THREAD

**Issue by joaopkuzma** [ProjetoSophiaDev/moodleplugins#2]
Olá Adriano!
Quando puder instalar este bloco e se possível deixar ele acessível sem a necessidade de Login.
A ideia é que se houver a necessidade de verificação do certificado ela seja feita.
Pelo que li em comentários ele permite levar o link deste bloco para a página inicial do Moodle. Ai quem precisar verificar a autenticidade pode fazer.
A princípio em consulta não achei versão mais recente, mas imagino que deva funcionar em nossa versão e com o nosso plugin de certificado: 
https://moodle.org/plugins/pluginversion.php?id=17958

**Comment by AdrianoRuseler** [comment]
Olá João, conforme conversamos, o plugin instalado atente a necessidade solicitada!
